### ISSUE TITLE
Entry for hc1 own program 1 switchtime

### ISSUE THREAD

**Issue by mwolle** [emsesp/EMS-ESP32#1424]
Hello, i want to change the following entry: "hc1 own program 1 switchtime". I used this syntay for entrys: 00 mo 06:30 on // 01 mo 17:30 off // 03 tu 06:30 on...-> moep the third entry will not safed, i get an error "Not found". I used a Buderus RC35 controller.

Input: 
![image](https://github.com/emsesp/EMS-ESP32/assets/26146678/ad831b0a-3ccf-47be-8cfb-9d9b28738205)

result:
![image](https://github.com/emsesp/EMS-ESP32/assets/26146678/fe5d47c1-b422-4434-a30d-c7f8e6654b4a)

**Comment by proddy** [comment]
I will try and reproduce. Please send system info (https://emsesp.github.io/docs/Support/) so I know which thermostat you are using.

**Comment by proddy** [comment]
I started writing some test code for this since I don't have an RC3x and there was nothing in our test.cpp. So glad you tried it out!

What also should work, is from the console (after a su) `call thermostat switchtime1 03 tu 06:30 on` and see what error comes back? We could also uncomment those LOG.WARN lines `Thermostat::set_switchtime()` to trace what is happening.

**Comment by mwolle** [comment]
I check the system version, i thought i had updated it on 3.6.2, but i test on 3.5.1. I update ESP to 3.6.2 and now i can enter the entrys without error. But after Update, i can't scroll the Entitylist.
But the major issue is solved with the 3.6.2 Update.
![image](https://github.com/emsesp/EMS-ESP32/assets/26146678/67fe6771-f32b-42ff-84c9-8a4ccfd49ff1)
