### ISSUE TITLE
Expose the device restart function via HA API 

### ISSUE THREAD

**Issue by ralle12345** [emsesp/EMS-ESP32#1641]
### PROBLEM DESCRIPTION

This is a feature request! I'd like to have the ems-esp32 device restart function that is available on the web-GUI exposed to a switch in teh HA API. This would let me restart the device from time to time as it's getting unresponsive after a certain operation time.

### REQUESTED INFORMATION

- [x] Searched the problem in [issues](https://github.com/emsesp/EMS-ESP32/issues)
- [x] Searched the problem in [discussions](https://github.com/emsesp/EMS-ESP32/discussions)
- [x] Searched the problem in the [docs](https://emsesp.github.io/docs/Troubleshooting/)
- [ ] Searched the problem in the [chat](https://discord.gg/3J3GgnzpyT)
- [ ] Provide the output of http://ems-esp.local/api/system :

### TO REPRODUCE

nothing to reproduce

### EXPECTED BEHAVIOUR

I would expect the ems-esp32 gateway to restart when the switch is triggered in the HA system.

**Comment by MichaelDvP** [comment]
> This would let me restart the device from time to time as it's getting unresponsive after a certain operation time.

I think if the device is unresponsive, it is unresponsive to mqtt too. But you can try: The mqtt command for restart is `/system/restart`, you can send any data. 
There was a long discussion about unresponsive devices, but it keeps in some cases unclear why this happens to few people. Some others have very bad wifi connection, sometimes because a wifi mesh hand the ems-esp to a weaker meshpoint. For this we have scheduler and you can add a schedule to restart the device daily/weekly/hourly/etc.

**Comment by ralle12345** [comment]
Ah! I didn't know about the possibility of scheduled restarts. I will try that next. My plan with the restart function was to restart the device from time to time even if it is responsive. Therefor the restart schedule should also do the trick on-device. I will check if I find the correct functionality and close this afterwards.

**Comment by ralle12345** [comment]
@MichaelDvP Thanks for the pointer in the right direction!

I found the correct command, but it was not easy to find in the docs. If someone else needs to restart the ems-esp by schedule - the command to do that is "**system/restart**"
