### ISSUE TITLE
Device specific commands

### ISSUE THREAD

**Issue by MichaelDvP** [emsesp/EMS-ESP32#1897]
There are some device specific commands that react different on devicetypes. I'm  thinking how to make a clear line:
- `api/devices/commands`
  is in line for all devices
- `api/device/values` 
 shows shortnames with values for all devices, missing for `system`
- `api/device/info`
  shows long names (set or user defined) for ems-devices.
  shows (user-defined, , no longnames needed) shortnames and  values for custom and scheduler, 
  show shortnames and values for system, no long names defined
  shows a list of value infos for analogsensor and temperaturesensor
-  `api/device/shortname`
  shows the device_value_info for a single shortname
- `api/device/entities`
  shows a list of `shortname: [longname, uom]`, only working on ems-devices

**My thoughts:** 
- Can we bring the `info` command in line for all devices, and show the same as `values` if there are no longnames
- Do the entities command have any usage for HA or something?
- Use the `entities` command or a new `config` for the list of attributes for all values like analogsensor/info now do.

Is this better als jsonObjects or jsonArray?
If we use named Objects we need a solution for empty names in scheduler (or make the names mandatory)

Example  as Array:
```
{
  "custom": [
    {
      "name": "mytemp",
      "storage": "ram",
      "type": "string",
      "readable": true,
      "writeable": true,
      "visible": true,
      "value": "0"
    },
    {
      "name": "hc2_test",
      "storage": "ram",
      "type": "string",
      "readable": true,
      "writeable": true,
      "visible": true,
      "value": "2"
    },
    {
      "name": "power",
      "storage": "ems",
      "type": "number",
      "uom": "%",
      "readable": true,
      "writeable": true,
      "visible": true,
      "device_id": "0x08",
      "type_id": "0x16",
      "offset": 2,
      "factor": 1
    }
  ]
}
```
as object it would look this way, maybe the better replacement for entities command
```
{
  "mytemp": {
    "name": "mytemp",
    "storage": "ram",
    "type": "string",
    "readable": true,
    "writeable": true,
    "visible": true,
    "value": "0"
  },
  "hc2_test": {
    "name": "hc2_test",
    "storage": "ram",
    "type": "string",
    "readable": true,
    "writeable": true,
    "visible": true,
    "value": "2"
  },
  "power": {
    "name": "power",
    "storage": "ems",
    "type": "number",
    "uom": "%",
    "readable": true,
    "writeable": true,
    "visible": true,
    "device_id": "0x08",
    "type_id": "0x16",
    "offset": 2,
    "factor": 1
  }
}
```
 @proddy What do you think?

**Comment by proddy** [comment]
I like it, the code does need a clean-up. My initial thoughts

- `<device>/command` - yes it should be consistent. There's a lot of repeated code, like manually adding values, info etc which I don't like. 
- Create a function that tests for `info` and `value` and other special commands. Now we have duplicate code doing string comparisons.
- add `system/values` as it is indeed missing
- `entities` I can't remember why I added it, but we don't need it now that we generate these using `dump_entites.sh`. I think we can comment out all that code and remove the command.
- JsonArray looks nicer, but JsonObject is easier to traverse and find objects in the JSON tree. E.g. just pick the node `custom[mytemp]` instead of looping through doing a string comparison on the `name` key.
- Decide if we want to nest or not, as there is a difference between `info` and `values`. For example

`ems-esp:# call thermostat info`
```json
{
  "hc1 selected room temperature (seltemp)": 23.0,
  "hc1 current room temperature (currtemp)": 20.7,
  "hc1 mqtt discovery current room temperature (haclimate)": "roomTemp",
  "hc1 mode type (modetype)": "comfort",
  "hc1 target flow temperature (targetflowtemp)": 0,
  "hc1 summer mode (summermode)": "winter",
  "hc1 room temperature from remote (remotetemp)": null,
  "hc1 room humidity from remote (remotehum)": null
}
```
`ems-esp:# call thermostat values`
```json
{
  "hc1": {
    "seltemp": 23.0,
    "currtemp": 20.7,
    "haclimate": "roomTemp",
    "modetype": "comfort",
    "targetflowtemp": 0,
    "summermode": "winter",
    "remotetemp": null,
    "remotehum": null
  },
  "dhw": {}
}
```

I would say nest, so the only different between values and info would be whether its the shortname or translated longname.

**Comment by MichaelDvP** [comment]
> Decide if we want to nest or not, as there is a difference between info and values. For example

Didn't remember this, but i think this a point for users don't like nested. We can use the same scheme for other devices. 
Custom/scheduler/analog/temperature does not have nests, so info/value stays the same, but for system we have then
system/info: `{"network rssi": -55}` and system/values gives `{"network": {"rssi": -55}}`
Then the default for `api/system` would also point to /values. So no change in response for @tp1de ioBroker

**Comment by proddy** [comment]
ok, makes sense.

I also think we can create a single function to find the attribute_s as this code is also repeated

**Comment by MichaelDvP** [comment]
I'll make a PR with some refactoring.

**Comment by proddy** [comment]
All done I think. The new tests pass. I'll close this one.
