### ISSUE TITLE
CS6800: Pump Differentiation between 'Primary' and 'Heating' Circuit 

### ISSUE THREAD

**Issue by vowill** [emsesp/EMS-ESP32#2001]
System setup:
Bosch CS6800iAW/WLW176i heatpump
Bosch controller UI800 (integrated in heatpump unit)
Bosch WLAN module K30RF
Bosch mixer MM100
System: 3.6.4 (ESP32-S3)

Issue:
The CS6800i has two integrated pumps:

1. PC0 = 'primary pump' for the coolant flow to the outside unit (and, when the dhw valve is activated, to the boiler)
2. PC1 = 'heating circuit pump' for the main heating circuit inside the building

These pumps are driven via a LIN bus, i. e. they are connected in parallel and triggered by a dedicated address via the LIN bus
(I checked the wiring in the CS6800i: The single LIN wire running out of the CS6800 controller is in fact split via an Y cable inside the wiring harness).

Even though the EMS-ESP adapter differentiates between these two pumps with regard to the PWM signal, the two values shown are always identical. That means the real differentiation as operated by the CS6800i is not visible via EMS-ESP.

### EXPECTED BEHAVIOUR
True separation of the two PWM signal values

**Comment by proddy** [comment]
Update first to the latest dev build and see if it's any better. There have been many changes and improvements in the last 10 months.

**Comment by UlfHRO** [comment]
Following custom entity works for my hp (Buderus WLW186i) additional to the already existing entities for PC0 (primary pump):
- PC0 flow in l/h: 0x08 | 0x0E4 | 36 | INT16

Following custom entities work for my hp for PC1 (heating circuit pump):
- PC1 flow in l/h: 0x08 | 0x2D6 | 9 | INT16
- PC1 rate in %: 0x08 | 0x488 | 13 | INT8
- PC1 running: 0x08 | 0x2D6 | 0 | INT8

**Comment by vowill** [comment]
@UlfHRO Thank you.
Unfortunately, no flow rate data (in l/h) is available in the WLW176i (I just added that controller type in my first comment).

**Comment by MichaelDvP** [comment]
@UlfHRO 

Thanks for the new entities.
Are the flow and rate values without factor? 
liters per hour seems uncommon, mostly we have l/min, but i can add the UOM to select it.
Is `PC1 running` a bool with 0/1 values or 0xFF for on?

**Comment by UlfHRO** [comment]
Hi Michael,
- Yes, flow is liter per hour, no factor... Same as indicated at the hp panel in service mode...
- rate is percent, no factor... Also same as indicated at the hp panel in service mode...
- pump running is "1", not running "0"...
Regards, Ulf

**Comment by UlfHRO** [comment]
one more thing...
for PC1 (heating circuit pump) the rate indicated is always "0%" even pump is running in normal diff pressure controlled mode (same as indicated on the hp panel)... Only if PC1 is controlled in "service test mode" at the hp panel (where you give a % command), then you see the rate feedback in %... So, the only meaningfull feedback for PC1 during normal operation is "running" and flow... But that gives a very good information about the room valves in the heating circuit...

**Comment by UlfHRO** [comment]
please see how it looks in my own app as an example...
![IMG_0380](https://github.com/user-attachments/assets/e004245c-2672-4ff5-9cee-474adf33f591)

**Comment by vowill** [comment]
> Update first to the latest dev build and see if it's any better.
At least the latest stable release (3.6.5) doesn't show any improvement.
Is v3.7.0 dev 38 already recommended for installation in a productive system?

**Comment by proddy** [comment]
> Is v3.7.0 dev 38 already recommended for installation in a productive system?

Yes

**Comment by vowill** [comment]
@proddy Just a remark:
I'm using the ioBroker software to visualize and control my heating system. With the version change from 3.6.x to 3.7.0 and the re-naming and addition of datapoints (mainly for dhw), a signifcant amount of adaptation in the ioBroker scripts and visualization became necessary.
I strongly recommend to highlight this fact when publising 3.7.0.

**Comment by proddy** [comment]
> @proddy Just a remark: I'm using the ioBroker software to visualize and control my heating system. With the version change from 3.6.x to 3.7.0 and the re-naming and addition of datapoints (mainly for dhw), a signifcant amount of adaptation in the ioBroker scripts and visualization became necessary. I strongly recommend to highlight this fact when publising 3.7.0.

@tp1de can you help me write a Breaking Change for the EMS-ESP Change Log on this? Or point to somewhere in your repo that explains the ioBroker changes and what needs to be done. Thanks.

**Comment by vowill** [comment]
@proddy Yes, I‘ll put together something over the weekend.

**Comment by tp1de** [comment]
The structure (name) changes within 3.7 do have an impact for all home automation systems. For HA as well.
Within the ioBroker adapter there are two alternatives to map the object names:
1.  1:1 from ems-esp API
2.  using the km200 (Buderus) functional structure which is independent from your device structure

Using (1) there will be now substructures within boiler and heating circuits for dhw. So all scripts and visualisations need to be adjusted
Using (2) there should be no significant changes, since all dhw entities are mapped to dhwCircuits.dhw1 as before, when using the actual stable adapter version. 

What needs to be mentioned that for MQTT discovery there is a selector to use 3.6 entity names. While migrating are you using this mqtt selector?

While changing names to 3.7 structure for all systems the history will be lost. Old values (HA statistics / ioBroker database entries) will be kept in database and not automatically deleted.

My general experience is that 99% of all end-users will not read breaking changes. 
Neither for ems-esp nor for ioBroker.
It should be sufficient to show the name changes for dhw within release notes.

I recognized that a lot of users where using the latest stable version of ems-esp while using the dev versions of the ioBroker adapter and the other way around (latest dev from ems-esp and stable from ioBroker). 
This brought up quite some instablity and/or questions. We might need to link the versions.

**Comment by proddy** [comment]
Thanks for explaining that Thomas. I agree, all we can do is place the breaking change in the release notes and mention it on the website for now, hoping someone will read it.

We could add something to the WebUI after an upgrade a pop-up dialog window saying "EMS-ESP has been upgraded. See <link> for the new features and any breaking changes", and keep showing this until they have hit Accept. But that's more code.
