### ISSUE TITLE
MQTT QoS 1 problematic

### ISSUE THREAD

**Issue by proddy** [emsesp/EMS-ESP32#305]
Thought I'd try out QoS and how well it performs after an outage. Turns out that it QoS 1 and 2 are not at all stable. After 45mins and 1500 publishes it just stops and the queue is not flushed. oops.

must fix!

**Comment by MichaelDvP** [comment]
I always use qos 1, but never had any issue. Steps to reproduce?

**Comment by proddy** [comment]
I just change the MQTT QoS setting to 1 and restarted for safe measure. After 45mins no more publishes. Queue is not full (it can take 300). I'll run some tests. Most likely in a wait state somewhere

**Comment by MichaelDvP** [comment]
I think i know what's wrong. You have implemented a qos check to wait for PUBACK in on_publish and stop sending until the the ack is received. But the  async_mqtt handles the qos completly and if ack is missing, it republishes with DUP and a new id. Then your routine waits forever for the first id. I think you can remove the on_publish-check completly. 

Regarding #335, i've tested with mosquitto and it's not easy. Standard setting is no clean session and subscribing to `homeassistant/#` does not cause the broker to send the retained data, because the client has to remember them with same session-id. We need a clean session set to make the broker send out the retained data. Also on connect all actual HA data removed and rebuild, his conflicts if we subscribe and wait for data.
To remove old HA data from broker we have to stop publishing HA configs, start a clean sessing, subscribe, wait for the data, and this takes some time, unsubscribe, reenable the publishing/HA creation. I think this takes to long to automate it on each start, better to implement a button to clean-up HA settings. 

Another thing i see with mosquitto: Publishing single values causes mosquitto to republish them back to emsesp, flooding it with known/unknown commands (`system/watch` is also published on command and pingpongs with the broker) . I have not found a way to stop this. Maybe it's better split command-subscriptions and publishes to different topics like tasmota do ( tasmota uses: `/stat/...` and `/cmnd/..` prefixes). I think of keep command topics, but change single publishes from `thermostat/hc1/seltemp`to `thermostat_data/hc1/seltemp`, etc.. Best as option if single publish is activated, because ioBroker-mqtt can handle the publish/subscribe to same topic as read/write entity.

**Comment by bbqkees** [comment]
If we can do the topic purge without any user interaction needed that would be the best option.
Having people use MQTT Explorer would only add to the complexity.

**Comment by proddy** [comment]
I need some time to digest all of this (I've been travelling much these past days). First thought reading this is to get rid of QOS 1 & 2 if it causes so many issues. I wrote that QOS1 code a while back trying to be smart but its not smart enough. 

And this new feature 'publish single topics' seems only useful for iobroker users (which is not a real MQTT server) so why not have an Integration type Home Assistant, Domoticz , IOBroker etc. 

I'm worried it's going to get complicated. Most users (and Kees would know) just fire it up, click on Home Assistant and off it goes.

**Comment by proddy** [comment]
and Michael, the investigation you put into this is superb seeing that you're not even a HA or Mosquitto user - much appreciated and as always, a big thanks for all your efforts here. 🥇

**Comment by MichaelDvP** [comment]
TL'DR: QoS works fine and always reconnects.

I've checked a bit more with a second emsesp connected to the heating (at 0x0D) and publishing to the spare raspi3 with mosquitto. With this configuration i can check longer disconnects without loosing data, the primary emsesp keep connceted to ioBroker. 
The actual logic for QoS works: if a response is missing the emsesp stops publishing until the queue overflows. This overflow removes the fist message with pending ack and the queue is sended out. Depending on publish times this can take a while.
Without the on_publish-check the library handles the ack, then a queue in the lib is filled (~50k) and afterwards the mqtt-queue with 300 messages(~50k). (This is the same as in QoS 0). With the on_publish check the lib does not queue, only the 300-mqtt-queue is filled.
I'm checking different types of disconnect: 
1. stop mosquitto, restart after short time (queue not overflowed)
2. stop mosquitto, wait >30 min before restart (queue overflow)
3. restart raspi
4. shutdown raspi and restart after >30 min
5. powercut raspi and reboot
6. powercut and wait >30min before repower
7. disconnect network cable short time
8. disconnect network cable long time

With QoS 1 i have all tests now, not always exactly the same duration, only changing something if i had a minute time.
In all cases it reconnects and sends the queued messages. In cases 1-4 the disconnect is instantly detected by emsesp. In cases 5-8 it takes 3 periods of keep-alive to detect the disconnect, in standard-setting (60sec) the disconnect is shown after 2-3 minutes. For very short disconnects before a keep-alive is missing, the reconnect happend immediatly, ~ a minute  disconnect waits for diconnect detected before the reconnect happend.
BTW: QoS 1 worked stable more than 24h before i started with disconnects, all publish times set to 10sec (factory default)

**Comment by MichaelDvP** [comment]
And:
9. disconnect/reconnect wifi on emsesp.

I've done this yesterday by changing wifi-tx-power a bit and lost one QoS 2 ack. I've seen this hours later that status was on last-will and queue around 250 messages, growing one message a minute (only heartbeat). 50 minutes later, when reaching the full queue publishing starts again. I think 5 hours waiting is a bit too long, should we add a timeout of, lets say, 10 minutes and resend or drop the message? 
But it's difficult to reproduce. Most of the time mqtt starts again on wifi reconnect.
BTW: with full queue and some long response messages in queue heap drops to 85k and system/info and system/settings respond with `null`. So #318 is memory related with the ethernet connection taking around 50k from heap.

**Comment by proddy** [comment]
closing, cannot reproduce
