### ISSUE TITLE
thermostat.minexttemp is missing (was available before in V3 and is still available in V2)

### ISSUE THREAD

**Issue by tp1de** [emsesp/EMS-ESP32#85]
As mentioned in #77 suddenly minexttemp is missing in thermostat.
The field is not shown anymore neither in WEB-UI nor by API V3. (since a week ?)

V2 API or WEB-UI still shows the field correctly.

The change of values was never working within my heating system with EMS+, RC310 and KB192i.
But at least the value set by RC310 was shown correctly - now not anymore.

**Comment by MichaelDvP** [comment]
This issue was already [fixed](https://github.com/emsesp/EMS-ESP32/commit/ae1e2eccd23f2a40957cc5db1129e67831129285#diff-406894b14369a14b21c12fe9db16f79f84595435a98826c4d7fe7bfc726691d3) after #77. The value was missing since [9.Jan.](https://github.com/emsesp/EMS-ESP32/commit/f6bdea10a5519d169b9221ff904bdd7c850f21e0#diff-406894b14369a14b21c12fe9db16f79f84595435a98826c4d7fe7bfc726691d3)
